use_frameworks!

platform :ios, '10.0'

target 'Clavier_Example' do
  pod 'Clavier', :path => '../'

  target 'Clavier_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 4.0.0'
    pod 'Nimble', '~> 9.2.0'
  end
end
